/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calendarapp.app;

public class App {

    public static void main(String[] args) {
        test();
    }
    
    public static void test() {
        TestTerminalGrid.start();
    }
}
